version: 0.2
            
phases:
  install:
    commands:
      - cd lambda && npm install -g serverless
      - npm install
      - cd ../client && npm install
  build:
    commands:
      - cd ../lambda && serverless deploy
