version: 0.2
            
phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - cd lambda && serverless package
  post_build:
    commands:
      - cd lambda && serverless deploy --package=.serverless/clickarino.zip
