version: 0.2
            
phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - serverless package
  post_build:
    commands:
      - serverless deploy --package=.serverless/clickarino.zip
